#!/bin/bash

#Nom du fichier à surveiller
NOM_FICHIER="/etc/crontab"

#Date de la dernière modification du fichier ci-dessus
DERNIERE_MODIF=$(date -r ${NOM_FICHIER} '+%d/%m/%Y %H:%M')

# Adresse mail de l'administrateur ou de la personne à prévenir
MAIL_ADMIN="root"

# Date a laquelle le fichier à bien été modifié par vos soins
DATE_MODIF=`cat /var/spool/cron/crontabs/Date`

# Test si les deux dates sont identiques
if [ "${DERNIERE_MODIF}" != "${DATE_MODIF}" ]; then

# Si différente, envoi du mail d'alerte
CORPS_MESSAGE="Alerte, le fichier ${NOM_FICHIER} modifie le ${DERNIERE_MODIF}";
echo "$CORPS_MESSAGE" | mail -s "Alerte modification fichier" "${MAIL_ADMIN}";
echo $DERNIERE_MODIF > /var/spool/cron/crontabs/Date
fi

# Date = /var/spool/cron/crontabs/Date
# les mails = /var/mail
# le fichier crontab = /etc/crontab
