#!/bin/bash

#Nom du fichier à surveiller
NOM_FICHIER="/var/spool/cron/crontabs"

# Date de la dernière modification du fichier ci-dessus
DERNIERE_MODIF=$(date -r ${NOM_FICHIER} '+%d/%m/%Y %H:%M')

# Adresse mail de l'administrateur ou de la personne à prévenir
MAIL_ADMIN="root"

# Date a laquelle le fichier à bien été modifié par vos soins
DATE_MODIF="09/02/2018 17:32"

# Test si les deux dates sont identiques
if [ "${NOM_FICHIER}" != "${DATE_MODIF}" ]; then

# Si différente, envoi du mail d'alerte
CORPS_MESSAGE="Alerte, le fichier ${NOM_FICHIER} modifié le ${DERNIERE_MODIF}";
echo "$CORPS_MESSAGE" | mail -s "Alerte modification fichier" "${MAIL_ADMIN}";
fi
